from Validations.validationData import ValidationData
class EstornoConsumoCombustivelLayout:         
    def table_name(self):
        return 'SCF_ESTORNOCONSUMOCOMBUSTIVEL'    
    def id_name_get(self):
        id_name = ValidationData()
        table = EstornoConsumoCombustivelLayout().table_name()
        name = id_name.search_id_name(table)
        return str(name).strip()
    
    def table_constraint(self):
        return ['CODENTIDADE', 'NRSEQUENCIAL'] #Automatizar identificação de constraint
    
    def columns_not_null_get(self):
        id_bem = EstornoConsumoCombustivelLayout()
        id = id_bem.id_name_get()
        return ['IDPARAMETERSYSTEM', 'NMPARAMETERSYSTEM', 'CODENTIDADE', 'IDMARCA', 'NMMARCA', 'IDESPECIE', 'NMESPECIE', 'IDMODELO', 'IDMARCA', 'NMMODELO', 'IDESPECIE', 'IDTIPOSERVICO', 'NMTIPOSERVICO', 'TPAGENDAMENTOSERVICO', 'CODPESSOA', 'NOME', 'CODTIPOPESSOA', 'DIGITO', 'ISUSUARIONFSE', 'IDMOTORISTA', 'CODENTIDADE', 'NRCODIGOMOTORISTA', 'IDMOTORISTACATCNH', 'IDMOTORISTA', 'IDCATEGORIACNH', 'IDMOTORISTASITUACAOCNH', 'IDMOTORISTA', 'DTSITUACAOCNH', 'IDSITUACAOCNH', 'NRPONTOSVIGENTES', 'IDVEICULO', 'IDMODELO', 'IDCOR', 'NRPASSAGEIRO', 'ISACUMULADORFUNCIONANDO', 'DTINCLUSAOSIMAM', 'NRCILINDRADAS', 'NRPOTENCIAMOTOR', 'NRCAPACIDADETANQUECOMB', 'NRCAPACIDADECARGA', 'IDCONSUMOCOMBUSTIVEL', 'CODENTIDADE', 'NRSEQUENCIAL', 'IDVEICULO', 'NRMES', 'NRANO', 'IDTIPOCATEGORIAOBJETODESPESA', 'IDTIPOOBJETODESPESA', 'NRQUANTIDADE', 'IDESTORNOCONSUMOCOMBUSTIVEL', 'IDCONSUMOCOMBUSTIVEL', 'CODENTIDADE', 'NRSEQUENCIAL', 'DATAESTORNO', 'MES', 'ANO']

    def columns_get(self):
        return ['VLPARAMETERSYSTEM', 'TPESPECIEACUMULADOR', 'IDCATEGORIACNH', 'TPVEICULOTCE', 'TPNATUREZABENS', 'TPCOMBUSTIVELTCE', 'ENDERECO', 'NUMERO', 'COMPLEMENTO', 'CIDADE', 'UF', 'CEP', 'EMAIL', 'TELEFONE', 'FAX', 'CELULAR', 'CODCARGO', 'CODENTIDADEORIGEM', 'CODPESSOAORIGEM', 'ENDERECOWEB', 'CODPESSOA_CONVERSAO', 'OLD_CODPESSOAINTEGRACAO', 'BAIRRO_OLD', 'BAIRRO', 'DATASINC', 'DSOBSERVACOES', 'EHESTRANGEIRO', 'DOCESTRANGEIRO', 'IDSERVIDOR', 'NRREGISTROCNH', 'DTPRIMEIRACNH', 'DTVALIDADECNH', 'TPMODELOCNH', 'DTEMISSAOCNH', 'CODPESSOAFISICA', 'ATIVO', 'CODENTIDADE', 'IDBEMOBRIGACAO', 'NRFROTA', 'NRPLACA', 'NRRENAVAM', 'NRCHASSI', 'NRMOTOR', 'NRANOFABRICACAO', 'NRANOMODELO', 'NRCILINDRADAS_OLD', 'NRPOTENCIAMOTOR_OLD', 'NRCAPACIDADETANQUECOMB_OLD', 'NRCAPACIDADECARGA_OLD', 'DSOBSERVACAO', 'TPVINCULO', 'IDFIPEMODELO', 'TPCOMBUSTIVEL', 'IDBEM', 'IDTPCATEGOBJETODESP', 'IDTPOBJETODESP', 'IMPRESSAODIARIOBORDO', 'MEDIACONSUMO', 'MOTIVO', 'NRQUANTIDADE'] 